# Generated by Django 4.2.1 on 2023-07-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0006_alter_reportcard_date_of_report_card_generation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='total_marks',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
